# must be unique in a given SonarQube instance
sonar.projectKey=JPETo-V8

# --- optional properties ---

sonar.scm.disabled=True

# defaults to project key
sonar.projectName=JPETo-Version-8
# defaults to 'not provided'
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.jdbc.username=sonar
sonar.jdbc.password=sonar
sonar.jdbc.url=jdbc:postgresql://sonar-postgres:5432/sonar